### PR TITLE
Added new post

### PR DESCRIPTION
**Pull request by byoigres**
Something weird using regular expressions.

### CODE REVIEW

**Comment by DTrejo** [comment]
merged your post! :) I have not deployed yet, but will soon, and I'll @mention you. Cheers!

**Comment by DTrejo** [comment]
@brianleroux can we maybe give @Zemnmez access to contribute to the repo? It could help to have more people merging & commenting on posts.

Cheers,
D

**Comment by schierlm** [comment]
Erm. That (using unicode codepoint order) is standard behaviour in Regex, and I have used `/[ -~]/` in multiple languages to check for ASCII printable characters (i. e. A or Z or $ but not € or Ç).

Unlike Oracle, which will use the configured collation order, and `/[ -~]/` will by default only match a bunch of special characters and no letters, while `/[A-Z]/` will match Ç (which sorts between C and D) and also x (which sorts like X).

The correct way to match uppercase or lowercase A-Z is `/[A-Za-z]/`.

**Comment by Zemnmez** [comment]
You're correct! I realised the code point order's ubiquity shortly after writing that comment, and I expected somewhat to be immediately called out on it. As for the correct way to match case insensitive A-Z, you're also right, but I don't think I said anything otherwise.

**Comment by schierlm** [comment]
I did not say that you said it; the [article on the front page](http://wtfjs.com/2014/01/29/regular-expression-and-slash), however, suggests that somebody may think this is the correct way to validate A-Z case-insensitively.

**Pull request closed without merging**
